### ISSUE TITLE
Tables no longer exist

### ISSUE THREAD

**Issue by AndrewRathbun** [kacos2000/Win10#3]
https://github.com/kacos2000/Win10/blob/2c04faf111de56748c52ef78028157fd48902107/YourPhone/yourphone_calls.sql#L23

It appears the DBs have changed over time, so this query may work on an older version of YourPhone, but not the current version.

**Comment by AndrewRathbun** [comment]
https://github.com/kacos2000/Win10/blob/953d46f46040a0869acee292b903b5a10bc0cfbe/YourPhone/yourphone_smsmms.sql#L42

Same here

**Comment by kacos2000** [comment]
Yeah, well YourPhone app has been updated lots of times since I wrote these queries, but the dBs are pretty straight forward so I didn't bother updating the queries.
